package org.davidCMs.vkengine.vk;

import static org.lwjgl.vulkan.VK14.*;

public enum VkBlendFactor {

	CONSTANT_ALPHA(VK_BLEND_FACTOR_CONSTANT_ALPHA),
	ONE(VK_BLEND_FACTOR_ONE),
	DST_COLOR(VK_BLEND_FACTOR_DST_COLOR),
	DST_ALPHA(VK_BLEND_FACTOR_DST_ALPHA),
	CONSTANT_COLOR(VK_BLEND_FACTOR_CONSTANT_COLOR),
	ONE_MINUS_CONSTANT_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA),
	ONE_MINUS_CONSTANT_COLOR(VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR),
	ONE_MINUS_DST_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA),
	ONE_MINUS_DST_COLOR(VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR),
	ONR_MINUS_SRC1_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA),
	ONR_MINUS_SRC1_COLOR(VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR),
	ONR_MINUS_SRC_ALPHA(VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA),
	ONR_MINUS_SRC_COLOR(VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR),
	SRC1_ALPHA(VK_BLEND_FACTOR_SRC1_ALPHA),
	SRC1_COLOR(VK_BLEND_FACTOR_SRC1_COLOR),
	SRC_ALPHA(VK_BLEND_FACTOR_SRC_ALPHA),
	SRC_ALPHA_SATURATE(VK_BLEND_FACTOR_SRC_ALPHA_SATURATE),
	SRC_COLOR(VK_BLEND_FACTOR_SRC_COLOR),
	ZERO(VK_BLEND_FACTOR_ZERO)

	;

	final int bit;

	VkBlendFactor(int bit) {
		this.bit = bit;
	}
}
