package org.davidCMs.vkengine.vk;

import static org.lwjgl.vulkan.VK14.*;

public enum VkDynamicState {

	BLEND_CONSTANTS(VK_DYNAMIC_STATE_BLEND_CONSTANTS),
	CULL_MODE(VK_DYNAMIC_STATE_CULL_MODE),
	DEPTH_BIAS(VK_DYNAMIC_STATE_DEPTH_BIAS),
	DEPTH_BOUNDS(VK_DYNAMIC_STATE_DEPTH_BOUNDS),
	DEPTH_COMPARE_OP(VK_DYNAMIC_STATE_DEPTH_COMPARE_OP),
	DEPTH_BIAS_ENABLE(VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE),
	DEPTH_BOUNDS_TEST_ENABLE(VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE),
	DEPTH_WRITE_ENABLE(VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE),
	FRONT_FACE(VK_DYNAMIC_STATE_FRONT_FACE),
	LINE_STIPPLE(VK_DYNAMIC_STATE_LINE_STIPPLE),
	LINE_WIDTH(VK_DYNAMIC_STATE_LINE_WIDTH),
	PRIMITIVE_RESTART_ENABLE(VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE),
	PRIMITIVE_TOPOLOGY(VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY),
	RASTERIZER_DISCARD_ENABLE(VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE),
	SCISSOR(VK_DYNAMIC_STATE_SCISSOR),
	SCISSOR_WITH_COUNT(VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT),
	STENCIL_COMPARE_MASK(VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK),
	STENCIL_OP(VK_DYNAMIC_STATE_STENCIL_OP),
	STENCIL_REFERENCE(VK_DYNAMIC_STATE_STENCIL_REFERENCE),
	STENCIL_TEST_ENABLE(VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE),
	STENCIL_WRITE_MASK(VK_DYNAMIC_STATE_STENCIL_WRITE_MASK),
	VERTEX_INPUT_BINDING_STRIDE(VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE),
	VIEWPORT(VK_DYNAMIC_STATE_VIEWPORT),
	VIEWPORT_WITH_COUNT(VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT)

	;

	final int bit;

	VkDynamicState(int bit) {
		this.bit = bit;
	}

}
