package org.davidCMs.vkengine.vk.deviceinfo;

import org.joml.Vector3f;
import org.joml.Vector3i;
import org.lwjgl.vulkan.VkPhysicalDeviceLimits;

public record VkEPhysicalDeviceLimits(
		int maxImageDimension1D,
		int maxImageDimension2D,
		int maxImageDimension3D,
		int maxImageDimensionCube,
		int maxImageArrayLayers,
		int maxTexelBufferElements,
		int maxUniformBufferRange,
		int maxStorageBufferRange,
		int maxPushConstantsSize,
		int maxMemoryAllocationCount,
		int maxSamplerAllocationCount,
		long bufferImageGranularity,
		long sparseAddressSpaceSize,
		int maxBoundDescriptorSets,
		int maxPerStageDescriptorSamplers,
		int maxPerStageDescriptorUniformBuffers,
		int maxPerStageDescriptorStorageBuffers,
		int maxPerStageDescriptorSampledImages,
		int maxPerStageDescriptorStorageImages,
		int maxPerStageDescriptorInputAttachments,
		int maxPerStageResources,
		int maxDescriptorSetSamplers,
		int maxDescriptorSetUniformBuffers,
		int maxDescriptorSetUniformBuffersDynamic,
		int maxDescriptorSetStorageBuffers,
		int maxDescriptorSetStorageBuffersDynamic,
		int maxDescriptorSetSampledImages,
		int maxDescriptorSetStorageImages,
		int maxDescriptorSetInputAttachments,
		int maxVertexInputAttributes,
		int maxVertexInputBindings,
		int maxVertexInputAttributeOffset,
		int maxVertexInputBindingStride,
		int maxVertexOutputComponents,
		int maxTessellationGenerationLevel,
		int maxTessellationPatchSize,
		int maxTessellationControlPerVertexInputComponents,
		int maxTessellationControlPerVertexOutputComponents,
		int maxTessellationControlPerPatchOutputComponents,
		int maxTessellationControlTotalOutputComponents,
		int maxTessellationEvaluationInputComponents,
		int maxTessellationEvaluationOutputComponents,
		int maxGeometryShaderInvocations,
		int maxGeometryInputComponents,
		int maxGeometryOutputComponents,
		int maxGeometryOutputVertices,
		int maxGeometryTotalOutputComponents,
		int maxFragmentInputComponents,
		int maxFragmentOutputAttachments,
		int maxFragmentDualSrcAttachments,
		int maxFragmentCombinedOutputResources,
		int maxComputeSharedMemorySize,
		Vector3i maxComputeWorkGroupCount,
		int maxComputeWorkGroupInvocations,
		Vector3i maxComputeWorkGroupSize,
		int subPixelPrecisionBits,
		int subTexelPrecisionBits,
		int mipMapPrecisionBits,
		int maxDrawIndexedIndexValue,
		int maxDrawIndirectCount,
		float maxSamplerLodBias,
		float maxSamplerAnisotropy,
		int maxViewports,
		Vector3i maxViewportDimensions,
		Vector3f viewportBoundsRange,
		int viewportSubPixelBits,
		long minMemoryMapAlignment,
		long minTexelBufferOffsetAlignment,
		long minUniformBufferOffsetAlignment,
		long minStorageBufferOffsetAlignment,
		int minTexelOffset,
		int maxTexelOffset,
		int minTexelGatherOffset,
		int maxTexelGatherOffset,
		float minInterpolationOffset,
		float maxInterpolationOffset,
		int subPixelInterpolationOffsetBits,
		int maxFramebufferWidth,
		int maxFramebufferHeight,
		int maxFramebufferLayers,
		int framebufferColorSampleCounts,
		int framebufferDepthSampleCounts,
		int framebufferStencilSampleCounts,
		int framebufferNoAttachmentsSampleCounts,
		int maxColorAttachments,
		int sampledImageColorSampleCounts,
		int sampledImageIntegerSampleCounts,
		int sampledImageDepthSampleCounts,
		int sampledImageStencilSampleCounts,
		int storageImageSampleCounts,
		int maxSampleMaskWords,
		boolean timestampComputeAndGraphics,
		float timestampPeriod,
		int maxClipDistances,
		int maxCullDistances,
		int maxCombinedClipAndCullDistances,
		int discreteQueuePriorities,
		Vector3f pointSizeRange,
		Vector3f lineWidthRange,
		float pointSizeGranularity,
		float lineWidthGranularity,
		boolean strictLines,
		boolean standardSampleLocations,
		long optimalBufferCopyOffsetAlignment,
		long optimalBufferCopyRowPitchAlignment,
		long nonCoherentAtomSize
) {
	public static VkEPhysicalDeviceLimits getFrom(VkPhysicalDeviceLimits limits) {

		return new VkEPhysicalDeviceLimits(
				limits.maxImageDimension1D(),
				limits.maxImageDimension2D(),
				limits.maxImageDimension3D(),
				limits.maxImageDimensionCube(),
				limits.maxImageArrayLayers(),
				limits.maxTexelBufferElements(),
				limits.maxUniformBufferRange(),
				limits.maxStorageBufferRange(),
				limits.maxPushConstantsSize(),
				limits.maxMemoryAllocationCount(),
				limits.maxSamplerAllocationCount(),
				limits.bufferImageGranularity(),
				limits.sparseAddressSpaceSize(),
				limits.maxBoundDescriptorSets(),
				limits.maxPerStageDescriptorSamplers(),
				limits.maxPerStageDescriptorUniformBuffers(),
				limits.maxPerStageDescriptorStorageBuffers(),
				limits.maxPerStageDescriptorSampledImages(),
				limits.maxPerStageDescriptorStorageImages(),
				limits.maxPerStageDescriptorInputAttachments(),
				limits.maxPerStageResources(),
				limits.maxDescriptorSetSamplers(),
				limits.maxDescriptorSetUniformBuffers(),
				limits.maxDescriptorSetUniformBuffersDynamic(),
				limits.maxDescriptorSetStorageBuffers(),
				limits.maxDescriptorSetStorageBuffersDynamic(),
				limits.maxDescriptorSetSampledImages(),
				limits.maxDescriptorSetStorageImages(),
				limits.maxDescriptorSetInputAttachments(),
				limits.maxVertexInputAttributes(),
				limits.maxVertexInputBindings(),
				limits.maxVertexInputAttributeOffset(),
				limits.maxVertexInputBindingStride(),
				limits.maxVertexOutputComponents(),
				limits.maxTessellationGenerationLevel(),
				limits.maxTessellationPatchSize(),
				limits.maxTessellationControlPerVertexInputComponents(),
				limits.maxTessellationControlPerVertexOutputComponents(),
				limits.maxTessellationControlPerPatchOutputComponents(),
				limits.maxTessellationControlTotalOutputComponents(),
				limits.maxTessellationEvaluationInputComponents(),
				limits.maxTessellationEvaluationOutputComponents(),
				limits.maxGeometryShaderInvocations(),
				limits.maxGeometryInputComponents(),
				limits.maxGeometryOutputComponents(),
				limits.maxGeometryOutputVertices(),
				limits.maxGeometryTotalOutputComponents(),
				limits.maxFragmentInputComponents(),
				limits.maxFragmentOutputAttachments(),
				limits.maxFragmentDualSrcAttachments(),
				limits.maxFragmentCombinedOutputResources(),
				limits.maxComputeSharedMemorySize(),
				new Vector3i(limits.maxComputeWorkGroupCount()),
				limits.maxComputeWorkGroupInvocations(),
				new Vector3i(limits.maxComputeWorkGroupSize()),
				limits.subPixelPrecisionBits(),
				limits.subTexelPrecisionBits(),
				limits.mipmapPrecisionBits(),
				limits.maxDrawIndexedIndexValue(),
				limits.maxDrawIndirectCount(),
				limits.maxSamplerLodBias(),
				limits.maxSamplerAnisotropy(),
				limits.maxViewports(),
				new Vector3i(limits.maxViewportDimensions()),
				new Vector3f(limits.viewportBoundsRange()),
				limits.viewportSubPixelBits(),
				limits.minMemoryMapAlignment(),
				limits.minTexelBufferOffsetAlignment(),
				limits.minUniformBufferOffsetAlignment(),
				limits.minStorageBufferOffsetAlignment(),
				limits.minTexelOffset(),
				limits.maxTexelOffset(),
				limits.minTexelGatherOffset(),
				limits.maxTexelGatherOffset(),
				limits.minInterpolationOffset(),
				limits.maxInterpolationOffset(),
				limits.subPixelInterpolationOffsetBits(),
				limits.maxFramebufferWidth(),
				limits.maxFramebufferHeight(),
				limits.maxFramebufferLayers(),
				limits.framebufferColorSampleCounts(),
				limits.framebufferDepthSampleCounts(),
				limits.framebufferStencilSampleCounts(),
				limits.framebufferNoAttachmentsSampleCounts(),
				limits.maxColorAttachments(),
				limits.sampledImageColorSampleCounts(),
				limits.sampledImageIntegerSampleCounts(),
				limits.sampledImageDepthSampleCounts(),
				limits.sampledImageStencilSampleCounts(),
				limits.storageImageSampleCounts(),
				limits.maxSampleMaskWords(),
				limits.timestampComputeAndGraphics(),
				limits.timestampPeriod(),
				limits.maxClipDistances(),
				limits.maxCullDistances(),
				limits.maxCombinedClipAndCullDistances(),
				limits.discreteQueuePriorities(),
				new Vector3f(limits.pointSizeRange()),
				new Vector3f(limits.lineWidthRange()),
				limits.pointSizeGranularity(),
				limits.lineWidthGranularity(),
				limits.strictLines(),
				limits.standardSampleLocations(),
				limits.optimalBufferCopyOffsetAlignment(),
				limits.optimalBufferCopyRowPitchAlignment(),
				limits.nonCoherentAtomSize()
		);
	}
}
