package dev.davidCMs.vkengine.vk;

import static org.lwjgl.vulkan.VK14.*;

public enum VkDescriptorType {

	COMBINED_IMAGE_SAMPLER(VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER),
	INLINE_UNIFORM_BLOCK(VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK),
	INPUT_ATTACHMENT(VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT),
	SAMPLED_IMAGE(VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE),
	SAMPLER(VK_DESCRIPTOR_TYPE_SAMPLER),
	STORAGE_BUFFER(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),
	STORAGE_BUFFER_DYNAMIC(VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC),
	STORAGE_IMAGE(VK_DESCRIPTOR_TYPE_STORAGE_IMAGE),
	STORAGE_TEXEL_BUFFER(VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER),
	UNIFORM_BUFFER(VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER),
	UNIFORM_BUFFER_DYNAMIC(VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC),
	UNIFORM_TEXEL_BUFFER(VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER)

	;

	final int bit;

	VkDescriptorType(int bit) {
		this.bit = bit;
	}
}
