package dev.davidCMs.vkengine.vk;

import org.lwjgl.vulkan.KHRSwapchain;

import static org.lwjgl.vulkan.KHRSwapchain.VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
import static org.lwjgl.vulkan.VK14.*;

public enum VkImageLayout {

	ATTACHMENT_OPTIMAL(VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL),
	COLOR_ATTACHMENT_OPTIMAL(VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL),
	DEPTH_ATTACHMENT_OPTIMAL(VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL),
	DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL(VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL),
	DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL(VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL),
	DEPTH_READ_ONLY_OPTIMAL(VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL),
	DEPTH_STENCIL_ATTACHMENT_OPTIMAL(VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL),
	DEPTH_STENCIL_READ_ONLY_OPTIMAL(VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL),
	GENERAL(VK_IMAGE_LAYOUT_GENERAL),
	PREINITIALIZED(VK_IMAGE_LAYOUT_PREINITIALIZED),
	READ_ONLY_OPTIMAL(VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL),
	RENDERING_LOCAL_READ(VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ),
	SHADER_READ_ONLY_OPTIMAL(VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL),
	STENCIL_ATTACHMENT_OPTIMAL(VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL),
	STENCIL_READ_ONLY_OPTIMAL(VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL),
	TRANSFER_DST_OPTIMAL(VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL),
	TRANSFER_SRC_OPTIMAL(VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL),
	UNDEFINED(VK_IMAGE_LAYOUT_UNDEFINED),

	PRESENT_SRC(VK_IMAGE_LAYOUT_PRESENT_SRC_KHR)

	;

	final int bit;

	VkImageLayout(int bit) {
		this.bit = bit;
	}
}
