package dev.davidCMs.vkengine.vk;

import static org.lwjgl.vulkan.VK14.*;

public enum VkLogicOp {

	AND(VK_LOGIC_OP_AND),
	NO_OP(VK_LOGIC_OP_NO_OP),
	OR(VK_LOGIC_OP_OR),
	COPY(VK_LOGIC_OP_COPY),
	CLEAR(VK_LOGIC_OP_CLEAR),
	AND_INVERTED(VK_LOGIC_OP_AND_INVERTED),
	AND_REVERSE(VK_LOGIC_OP_AND_REVERSE),
	COPY_INVERTED(VK_LOGIC_OP_COPY_INVERTED),
	EQUIVALENT(VK_LOGIC_OP_EQUIVALENT),
	INVERT(VK_LOGIC_OP_INVERT),
	NAND(VK_LOGIC_OP_NAND),
	NOR(VK_LOGIC_OP_NOR),
	OR_INVERTED(VK_LOGIC_OP_OR_INVERTED),
	OR_REVERSE(VK_LOGIC_OP_OR_REVERSE),
	SET(VK_LOGIC_OP_SET),
	XOR(VK_LOGIC_OP_XOR)

	;

	final int bit;

	VkLogicOp(int bit) {
		this.bit = bit;
	}

}
