package dev.davidCMs.vkengine.graphics.vk;

import static org.lwjgl.vulkan.VK14.*;

public enum VkPrimitiveTopology {

	POINT_LIST(VK_PRIMITIVE_TOPOLOGY_POINT_LIST),
	LINE_LIST(VK_PRIMITIVE_TOPOLOGY_LINE_LIST),
	LINE_STRIP(VK_PRIMITIVE_TOPOLOGY_LINE_STRIP),
	LINE_LIST_WITH_ADJACENCY(VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY),
	LINE_STRIP_WITH_ADJACENCY(VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY),
	PATCH_LIST(VK_PRIMITIVE_TOPOLOGY_PATCH_LIST),
	TRIANGLE_FAN(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN),
	TRIANGLE_LIST(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST),
	TRIANGLE_STRIP(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP),
	TRIANGLE_LIST_WITH_ADJACENCY(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY),
	TRIANGLE_STRIP_WITH_ADJACENCY(VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY),

	;

	final int bit;

	VkPrimitiveTopology(int bit) {
		this.bit = bit;
	}

}
